modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory
license = "MIT"

[[mods]] #mandatory
modId = "trimmable_tools" #mandatory
version = "${version}" #mandatory
displayName = "Trimmable Tools" #mandatory
logoFile = "pack.png"
authors = "Apollo, DawnKiro" #optional
description = "Trim your tools!"


[[dependencies.trimmable_tools]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.trimmable_tools]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1, 1.20.2)"
ordering = "NONE"
side = "BOTH"
