modLoader = 'lowcodefml'
loaderVersion = '[46,)'
license="MIT"

[[mods]]
  modId="trimmable_tools"
  version="1.0.4"
  displayName="Trimmable Tools"
  logoFile="pack.png"
  authors="Apollo"
  description='''
  Trim your tools with the updated smithing table!
  '''

  [[dependencies.trimmable_tools]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.trimmable_tools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
